# Generated by Django 4.2.4 on 2023-09-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
