# Generated by Django 4.2.4 on 2023-09-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_app', '0002_customuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='display_pic',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
