# Generated by Django 4.2.4 on 2023-09-01 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_app', '0004_alter_customuser_address_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.BigIntegerField(null=True, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
