# Generated by Django 4.2.3 on 2023-09-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_app', '0007_categories_customerorders_productreviews_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_long_description',
        ),
    ]
