# Generated by Django 4.2.3 on 2023-09-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_app', '0008_remove_products_product_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='thumbnail',
            field=models.FileField(upload_to='images/'),
        ),
    ]
