# Generated by Django 4.2.4 on 2023-09-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_app', '0009_alter_subcategories_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttags',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productvarientitems',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productvarientitems',
            name='product_varient_id',
        ),
        migrations.DeleteModel(
            name='ProductAbout',
        ),
        migrations.DeleteModel(
            name='ProductTags',
        ),
        migrations.DeleteModel(
            name='ProductVarient',
        ),
        migrations.DeleteModel(
            name='ProductVarientItems',
        ),
    ]
