# Generated by Django 4.2.3 on 2023-09-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='varient',
            new_name='variant',
        ),
    ]
