# Generated by Django 4.2.3 on 2023-09-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_alter_brand_brand_image_alter_categories_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
