# Generated by Django 4.2.3 on 2023-09-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_alter_cart_items_alter_cartitem_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variant',
            new_name='products',
        ),
    ]
