# Generated by Django 4.2.3 on 2023-09-26 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_discount_inventory_rename_title_categories_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='inventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.inventory'),
        
        ),
    ]
