# Generated by Django 4.2.3 on 2023-09-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_rename_variant_orderitem_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
